<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>module.deterministic-model</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Assets/modules/module.deterministic-model/src/Deterministic.Model/**/*.cs" />
  </ItemGroup>
</Project>
