<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Module.Verification.Diagnostics</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Assets/modules/module.verification/Module.Verification.Diagnostics/src/Diagnostics/**/*.cs" Exclude="../../../Assets/modules/module.verification/Module.Verification.Diagnostics/src/Diagnostics/**/obj/**/*.cs;../../../Assets/modules/module.verification/Module.Verification.Diagnostics/src/Diagnostics/**/bin/**/*.cs" />
  </ItemGroup>
</Project>
