<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Module.WaveDispatcher</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Assets/modules/module.wave-dispatcher/src/**/*.cs" />

  </ItemGroup>
</Project>
